# Uncomment the next line to define a global platform for your project
platform :ios, '18.4'

target 'Scheduling' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  target 'SchedulingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SchedulingUITests' do
    # Pods for testing
  end

end
